# Generated by Django 5.2.17 on 2026-09-20 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('phone', 'Phone'), ('nin', 'Nin')], max_length=5)),
                ('value', models.CharField(max_length=20)),
                ('holder_type', models.CharField(choices=[('proposal', 'Proposal'), ('staff', 'Staff')], max_length=10)),
                ('holder_id', models.CharField(max_length=128)),
                ('holder_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_claims', to='schools.school')),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'holder_type', 'holder_id'], name='staff_ident_school__de268b_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'kind', 'value'), name='one_holder_per_number')],
            },
        ),
    ]
