# Generated by Django 5.2.17 on 2026-10-01 10:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_alumni_verification_event'),
        ('schools', '0005_school_organization_type_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time_text', models.CharField(blank=True, max_length=40)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alumni_events', to='schools.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_events', to='schools.school')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlumniEventRsvp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attending', models.BooleanField()),
                ('responded_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='alumni.alumnievent')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_event_rsvps', to='schools.membership')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'membership'), name='one_rsvp_per_alumnus_per_event')],
            },
        ),
    ]
