# Generated by Django 5.2.17 on 2026-10-01 11:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_alumnievent_alumnieventrsvp'),
        ('schools', '0005_school_organization_type_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniPledge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('volunteering', 'Volunteering'), ('mentoring', 'Mentoring'), ('supplies', 'Supplies & Materials'), ('speaking', 'Guest Speaking'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('offered', 'Offered'), ('acknowledged', 'Acknowledged'), ('fulfilled', 'Fulfilled'), ('withdrawn', 'Withdrawn')], default='offered', max_length=20)),
                ('school_note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_pledges', to='schools.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_pledges', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
