# Generated by Django 5.2.17 on 2026-09-20 20:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_school_official_email_school_official_sender_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_id', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=20)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked')], default='pending', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_invitations', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvitationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='invitations.staffinvitation')),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StaffLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=128)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('linked_via', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='invitations.staffinvitation')),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_link', to='schools.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_links', to='schools.school')),
            ],
        ),
        migrations.AddIndex(
            model_name='staffinvitation',
            index=models.Index(fields=['school', 'staff_id'], name='invitations_school__7834ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('school', 'staff_id'), name='one_pending_invitation_per_staff'),
        ),
        migrations.AddConstraint(
            model_name='stafflink',
            constraint=models.UniqueConstraint(fields=('school', 'staff_id'), name='one_login_per_staff_record'),
        ),
    ]
