# Generated by Django 5.2.17 on 2026-09-20 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffinvitation',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
