# Generated by Django 5.2.17 on 2026-09-26 05:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0005_school_organization_type_location'),
        ('students', '0003_student_guardian_account_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32)),
                ('display_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=12)),
                ('origin', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='schools.school')),
            ],
            options={
                'verbose_name_plural': 'families',
                'ordering': ['display_name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='FamilyGuardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary_payer', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guardians', to='receivables.family')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='family_links', to='students.guardianlink')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
            ],
            options={
                'ordering': ['-is_primary_payer', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FamilyStudent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='receivables.family')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='family_memberships', to='students.student')),
            ],
            options={
                'ordering': ['joined_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FinanceAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=48)),
                ('object_type', models.CharField(max_length=40)),
                ('object_id', models.CharField(max_length=64)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
            ],
            options={
                'ordering': ['-at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['school', 'status'], name='receivables_school__41854b_idx'),
        ),
        migrations.AddConstraint(
            model_name='family',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='unique_family_code_per_school'),
        ),
        migrations.AddConstraint(
            model_name='family',
            constraint=models.UniqueConstraint(condition=models.Q(('origin', ''), _negated=True), fields=('school', 'origin'), name='unique_family_origin_per_school'),
        ),
        migrations.AddConstraint(
            model_name='familyguardian',
            constraint=models.UniqueConstraint(fields=('family', 'guardian'), name='one_link_per_family_guardian'),
        ),
        migrations.AddConstraint(
            model_name='familyguardian',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary_payer', True)), fields=('family',), name='one_primary_payer_per_family'),
        ),
        migrations.AddIndex(
            model_name='familystudent',
            index=models.Index(fields=['school', 'family', 'is_active'], name='receivables_school__14b48b_idx'),
        ),
        migrations.AddConstraint(
            model_name='familystudent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student',), name='one_active_family_per_student'),
        ),
        migrations.AddConstraint(
            model_name='familystudent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_active', True), ('left_at__isnull', True)), models.Q(('is_active', False), ('left_at__isnull', False)), _connector='OR'), name='family_student_left_matches_active'),
        ),
        migrations.AddIndex(
            model_name='financeauditevent',
            index=models.Index(fields=['school', '-at'], name='receivables_school__d12743_idx'),
        ),
        migrations.AddIndex(
            model_name='financeauditevent',
            index=models.Index(fields=['school', 'object_type', 'object_id'], name='receivables_school__7893fb_idx'),
        ),
    ]
