# Generated by Django 5.2.17 on 2026-09-26 05:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_elective_selection_history'),
        ('receivables', '0001_families_and_audit'),
        ('schools', '0005_school_organization_type_location'),
        ('students', '0003_student_guardian_account_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], default='draft', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('retire_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacements', to='receivables.feeschedule')),
                ('retired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_schedules', to='schools.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_schedules', to='academics.academicsession')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_schedules', to='academics.academicterm')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FeeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('tuition', 'Tuition'), ('ict', 'ICT'), ('levy', 'Development levy'), ('books', 'Books'), ('transport', 'Transport'), ('meals', 'Meals'), ('examination', 'Examination'), ('uniform', 'Uniform'), ('other', 'Other')], default='other', max_length=16)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('plan', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('scope', models.CharField(choices=[('all', 'Every student'), ('section', 'An academic section'), ('class', 'One class'), ('student', 'One student')], default='all', max_length=8)),
                ('section', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.academicclass')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='students.student')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='receivables.feeschedule')),
            ],
            options={
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentReceivable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=40)),
                ('item_name', models.CharField(max_length=120)),
                ('item_category', models.CharField(choices=[('tuition', 'Tuition'), ('ict', 'ICT'), ('levy', 'Development levy'), ('books', 'Books'), ('transport', 'Transport'), ('meals', 'Meals'), ('examination', 'Examination'), ('uniform', 'Uniform'), ('other', 'Other')], max_length=16)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('gross_amount_minor', models.BigIntegerField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('partially_paid', 'Partly paid'), ('settled', 'Settled'), ('void', 'Void')], default='open', max_length=16)),
                ('charge_key', models.UUIDField(default=uuid.uuid4)),
                ('installment_number', models.PositiveSmallIntegerField(default=1)),
                ('installment_count', models.PositiveSmallIntegerField(default=1)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='receivables.family')),
                ('fee_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='receivables.feeitem')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='receivables.feeschedule')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivables', to='schools.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='students.student')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.academicterm')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
            ],
            options={
                'ordering': ['due_date', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReceivableAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('scholarship', 'Scholarship'), ('discount', 'Discount'), ('waiver', 'Waiver'), ('correction', 'Correction'), ('other', 'Other')], max_length=16)),
                ('amount_minor', models.BigIntegerField()),
                ('reason', models.CharField(max_length=300)),
                ('group_id', models.UUIDField(blank=True, null=True)),
                ('authorized_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_ref', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
                ('reverses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='receivables.receivableadjustment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
                ('receivable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='receivables.studentreceivable')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='feeschedule',
            index=models.Index(fields=['school', 'status'], name='receivables_school__3ca31f_idx'),
        ),
        migrations.AddConstraint(
            model_name='feeschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'retired'), _negated=True), fields=('school', 'session', 'term', 'name'), name='unique_live_fee_schedule_name'),
        ),
        migrations.AddConstraint(
            model_name='feeschedule',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'retired']), ('published_at__isnull', False), _connector='OR'), name='fee_schedule_published_has_a_time'),
        ),
        migrations.AddConstraint(
            model_name='feeitem',
            constraint=models.UniqueConstraint(fields=('schedule', 'code'), name='unique_fee_item_code_per_schedule'),
        ),
        migrations.AddConstraint(
            model_name='feeitem',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='fee_item_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='feeitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('academic_class__isnull', True), ('scope', 'all'), ('section', ''), ('student__isnull', True)), models.Q(('academic_class__isnull', True), ('scope', 'section'), ('student__isnull', True), models.Q(('section', ''), _negated=True)), models.Q(('academic_class__isnull', False), ('scope', 'class'), ('section', ''), ('student__isnull', True)), models.Q(('academic_class__isnull', True), ('scope', 'student'), ('section', ''), ('student__isnull', False)), _connector='OR'), name='fee_item_scope_matches_its_target'),
        ),
        migrations.AddConstraint(
            model_name='feeitem',
            constraint=models.CheckConstraint(condition=models.Q(('scope', 'student'), ('is_mandatory', True), _connector='OR'), name='optional_fee_item_targets_students'),
        ),
        migrations.AddIndex(
            model_name='studentreceivable',
            index=models.Index(fields=['school', 'family', 'status'], name='receivables_school__cfeaa2_idx'),
        ),
        migrations.AddIndex(
            model_name='studentreceivable',
            index=models.Index(fields=['school', 'student', 'status'], name='receivables_school__9d75c7_idx'),
        ),
        migrations.AddIndex(
            model_name='studentreceivable',
            index=models.Index(fields=['school', 'due_date'], name='receivables_school__257e80_idx'),
        ),
        migrations.AddIndex(
            model_name='studentreceivable',
            index=models.Index(fields=['charge_key'], name='receivables_charge__42a3a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentreceivable',
            constraint=models.UniqueConstraint(fields=('fee_item', 'student', 'installment_number'), name='one_receivable_per_item_student_instalment'),
        ),
        migrations.AddConstraint(
            model_name='studentreceivable',
            constraint=models.CheckConstraint(condition=models.Q(('gross_amount_minor__gt', 0)), name='receivable_gross_positive'),
        ),
        migrations.AddConstraint(
            model_name='studentreceivable',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'void'), ('voided_at__isnull', False)), models.Q(models.Q(('status', 'void'), _negated=True), ('voided_at__isnull', True)), _connector='OR'), name='receivable_void_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='studentreceivable',
            constraint=models.CheckConstraint(condition=models.Q(('installment_number__gte', 1), ('installment_number__lte', models.F('installment_count'))), name='receivable_instalment_in_range'),
        ),
        migrations.AddIndex(
            model_name='receivableadjustment',
            index=models.Index(fields=['school', 'receivable'], name='receivables_school__c3f5e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='receivableadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='adjustment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='receivableadjustment',
            constraint=models.UniqueConstraint(condition=models.Q(('source_ref', ''), _negated=True), fields=('receivable', 'source_ref'), name='one_adjustment_per_source_per_receivable'),
        ),
    ]
