# Generated by Django 5.2.17 on 2026-09-26 05:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_elective_selection_history'),
        ('bankconnect', '0003_family_and_receivable_links'),
        ('receivables', '0002_fees_receivables_adjustments'),
        ('schools', '0005_school_organization_type_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyCollectionAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=40)),
                ('external_account_ref', models.CharField(blank=True, max_length=120)),
                ('account_number', models.CharField(blank=True, max_length=40)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('provisioning', 'Being set up'), ('active', 'Active'), ('dormant', 'Dormant'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='provisioning', max_length=14)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('dormant_at', models.DateTimeField(blank=True, null=True)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('provider_meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bankconnect.bankconnection')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_accounts', to='receivables.family')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['school', 'family', 'status'], name='receivables_school__058164_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('account_number', ''), _negated=True), fields=('school', 'provider', 'account_number'), name='one_family_account_per_number'), models.UniqueConstraint(condition=models.Q(('external_account_ref', ''), _negated=True), fields=('school', 'provider', 'external_account_ref'), name='one_family_account_per_provider_ref'), models.UniqueConstraint(condition=models.Q(('status', 'closed'), _negated=True), fields=('family', 'provider'), name='one_live_account_per_family_and_provider')],
            },
        ),
        migrations.CreateModel(
            name='FamilyCreditEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('overpayment', 'Overpayment'), ('released', 'Released from a charge'), ('application_reversed', 'Application reversed'), ('applied', 'Applied to a charge'), ('refunded', 'Refunded'), ('overpayment_reversed', 'Payment reversed')], max_length=24)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('ref', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_entries', to='receivables.family')),
                ('receivable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_entries', to='receivables.studentreceivable')),
                ('reverses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='receivables.familycreditentry')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_entries', to='bankconnect.banktransaction')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['school', 'family', 'kind'], name='receivables_school__ef7b77_idx'), models.Index(fields=['transaction', 'kind'], name='receivables_transac_df3012_idx'), models.Index(fields=['receivable', 'kind'], name='receivables_receiva_95b635_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='credit_entry_amount_positive'), models.UniqueConstraint(condition=models.Q(('ref', ''), _negated=True), fields=('school', 'ref'), name='one_credit_entry_per_ref')],
            },
        ),
        migrations.CreateModel(
            name='FamilyStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('void', 'Void')], default='issued', max_length=8)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='receivables.family')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.academicsession')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.academicterm')),
            ],
            options={
                'ordering': ['-issued_at', '-id'],
                'indexes': [models.Index(fields=['school', 'family', '-issued_at'], name='receivables_school__b830b7_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'number'), name='unique_statement_number_per_school')],
            },
        ),
    ]
