# Generated by Django 5.2.17 on 2026-09-26 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0003_credit_ledger_collection_accounts_statements'),
        ('schools', '0005_school_organization_type_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='familycollectionaccount',
            name='public_details',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='familystatement',
            name='void_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='familystatement',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familystatement',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership'),
        ),
    ]
