# Generated by Django 5.2.17 on 2026-09-26 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0004_family_account_details_and_statement_void'),
        ('schools', '0005_school_organization_type_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='merged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_families', to='receivables.family'),
        ),
        migrations.AddConstraint(
            model_name='family',
            constraint=models.CheckConstraint(condition=models.Q(('merged_into', models.F('id')), _negated=True), name='family_not_merged_into_itself'),
        ),
    ]
