from django.urls import path

from .views import (
    ApproveAssociationMemberView,
    AssociationCatalogView,
    AssociationMembersView,
    CancelVerificationRequestView,
    ExitAssociationMembershipView,
    JoinAssociationView,
    NetworkPhoneMatchView,
    ReceivedVerificationRequestsView,
    RejectAssociationMemberView,
    RespondVerificationRequestView,
    SchoolAssociationMembershipsView,
    SendVerificationRequestView,
    SentVerificationRequestsView,
    SuspendAssociationMemberView,
)

urlpatterns = [
    path("transferverify/associations/", AssociationCatalogView.as_view()),
    path(
        "schools/<uuid:school_id>/transferverify/associations/",
        SchoolAssociationMembershipsView.as_view(),
    ),
    path(
        "schools/<uuid:school_id>/transferverify/associations/<uuid:association_id>/join/",
        JoinAssociationView.as_view(),
    ),
    path(
        "schools/<uuid:school_id>/transferverify/associations/memberships/<uuid:membership_id>/exit/",
        ExitAssociationMembershipView.as_view(),
    ),
    path(
        "transferverify/associations/<uuid:association_id>/members/",
        AssociationMembersView.as_view(),
    ),
    path(
        "transferverify/associations/<uuid:association_id>/members/<uuid:membership_id>/approve/",
        ApproveAssociationMemberView.as_view(),
    ),
    path(
        "transferverify/associations/<uuid:association_id>/members/<uuid:membership_id>/reject/",
        RejectAssociationMemberView.as_view(),
    ),
    path(
        "transferverify/associations/<uuid:association_id>/members/<uuid:membership_id>/suspend/",
        SuspendAssociationMemberView.as_view(),
    ),
    path(
        "schools/<uuid:school_id>/transferverify/network/match/",
        NetworkPhoneMatchView.as_view(),
    ),
    path(
        "schools/<uuid:school_id>/transferverify/network/requests/",
        SendVerificationRequestView.as_view(),
    ),
    path(
        "schools/<uuid:school_id>/transferverify/network/requests/sent/",
        SentVerificationRequestsView.as_view(),
    ),
    path(
        "schools/<uuid:school_id>/transferverify/network/requests/received/",
        ReceivedVerificationRequestsView.as_view(),
    ),
    path(
        "schools/<uuid:school_id>/transferverify/network/requests/<uuid:request_id>/respond/",
        RespondVerificationRequestView.as_view(),
    ),
    path(
        "schools/<uuid:school_id>/transferverify/network/requests/<uuid:request_id>/cancel/",
        CancelVerificationRequestView.as_view(),
    ),
]
