# Generated by Django 5.2.17 on 2026-09-24 22:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_elective_selection_history'),
        ('schools', '0005_school_organization_type_location'),
        ('students', '0003_student_guardian_account_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=128)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for review'), ('reviewed', 'Reviewed'), ('released', 'Released')], default='draft', max_length=16)),
                ('overall_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overall_grade', models.CharField(blank=True, max_length=4)),
                ('class_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('class_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('attendance_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('principal_comment', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_cards', to='academics.academicclass')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_report_cards', to='schools.membership')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='released_report_cards', to='schools.membership')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_report_cards', to='schools.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_cards', to='students.student')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_report_cards', to='schools.membership')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_cards', to='academics.academicterm')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReportCardEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=24)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_card_events', to='schools.membership')),
                ('report_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='report_cards.reportcard')),
            ],
            options={
                'ordering': ['-revision'],
            },
        ),
        migrations.CreateModel(
            name='ReportCardSubjectLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weighted_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, max_length=4)),
                ('assessments_included', models.PositiveIntegerField(default=0)),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_card_lines', to='academics.classsubject')),
                ('report_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='report_cards.reportcard')),
            ],
            options={
                'ordering': ['class_subject__subject__name'],
            },
        ),
        migrations.AddIndex(
            model_name='reportcard',
            index=models.Index(fields=['academic_class', 'term', 'state'], name='report_card_class_term_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportcard',
            constraint=models.UniqueConstraint(fields=('school', 'external_id'), name='report_card_external_uq'),
        ),
        migrations.AddConstraint(
            model_name='reportcard',
            constraint=models.UniqueConstraint(fields=('student', 'term'), name='report_card_student_term_uq'),
        ),
        migrations.AddConstraint(
            model_name='reportcardevent',
            constraint=models.UniqueConstraint(fields=('report_card', 'revision'), name='report_card_event_revision_uq'),
        ),
        migrations.AddConstraint(
            model_name='reportcardsubjectline',
            constraint=models.UniqueConstraint(fields=('report_card', 'class_subject'), name='report_card_line_uq'),
        ),
    ]
