# Generated by Django 5.2.17 on 2026-09-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='class_teacher_comment',
            field=models.TextField(blank=True),
        ),
    ]
