# Generated by Django 5.2.17 on 2026-09-20 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=253, unique=True)),
                ('kind', models.CharField(choices=[('platform', 'Platform'), ('custom', 'Custom')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('disabled', 'Disabled')], default='pending', max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='schools.school')),
            ],
            options={
                'ordering': ['school__name', '-is_primary', 'host'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('school',), name='one_primary_domain_per_school'), models.CheckConstraint(condition=models.Q(('is_primary', False), ('status', 'verified'), _connector='OR'), name='primary_domain_must_be_verified')],
            },
        ),
    ]
