# Generated by Django 5.2.17 on 2026-09-26 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_elective_selection_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentsubjectselection',
            options={'ordering': ['class_subject__subject__name', '-selected_at']},
        ),
    ]
