# Generated by Django 5.2.17 on 2026-09-24 23:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_elective_selection_history'),
        ('schools', '0005_school_organization_type_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTeacherAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=64)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('handover_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_teacher_assignments', to='academics.academicclass')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
                ('previous_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handover_successors', to='class_teachers.classteacherassignment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_assignments', to='schools.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_teacher_assignments', to='academics.academicsession')),
                ('teacher_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_teacher_assignments', to='schools.membership')),
            ],
            options={
                'ordering': ['-started_at', '-created_at'],
                'indexes': [models.Index(fields=['teacher_membership', 'ended_at'], name='clsteach_member_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'external_id'), name='class_teacher_external_uq'), models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('academic_class', 'session'), name='clsteach_active_class_uq')],
            },
        ),
    ]
