# Generated by Django 5.2.17 on 2026-09-25 07:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_elective_selection_history'),
        ('schools', '0005_school_organization_type_location'),
        ('students', '0003_student_guardian_account_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='CbtTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=128)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=16)),
                ('title', models.CharField(blank=True, max_length=240)),
                ('duration_minutes', models.PositiveIntegerField(default=15)),
                ('instructions', models.TextField(blank=True)),
                ('result_mode', models.CharField(choices=[('score_only', 'Score only'), ('score_and_answers', 'Score and correct answers')], default='score_only', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_cbt_tests', to='schools.membership')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cbt_tests', to='academics.classsubject')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_cbt_tests', to='schools.membership')),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edited_cbt_tests', to='schools.membership')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_cbt_tests', to='schools.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbt_tests', to='schools.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cbt_tests', to='academics.academicterm')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CbtRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_code', models.CharField(max_length=80)),
                ('student_name', models.CharField(max_length=320)),
                ('admission_number', models.CharField(blank=True, max_length=80)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cbt_recipients', to='students.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipients', to='cbt.cbttest')),
            ],
            options={
                'ordering': ['student_name', 'student_code'],
            },
        ),
        migrations.CreateModel(
            name='CbtQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('prompt', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('correct_index', models.PositiveSmallIntegerField()),
                ('explanation', models.TextField(blank=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cbt.cbttest')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='CbtEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=24)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cbt_events', to='schools.membership')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='cbt.cbttest')),
            ],
            options={
                'ordering': ['-revision'],
            },
        ),
        migrations.CreateModel(
            name='CbtAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=128)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('answers', models.JSONField(default=list)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbt_attempts', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cbt_attempts', to='students.student')),
                ('recipient', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='attempt', to='cbt.cbtrecipient')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='cbt.cbttest')),
            ],
            options={
                'ordering': ['-submitted_at', 'student__surname', 'student__first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='cbttest',
            index=models.Index(fields=['school', 'state'], name='cbt_test_school_state_idx'),
        ),
        migrations.AddIndex(
            model_name='cbttest',
            index=models.Index(fields=['class_subject', 'term', 'state'], name='cbt_test_subject_term_idx'),
        ),
        migrations.AddConstraint(
            model_name='cbttest',
            constraint=models.UniqueConstraint(fields=('school', 'external_id'), name='cbt_test_external_uq'),
        ),
        migrations.AddIndex(
            model_name='cbtrecipient',
            index=models.Index(fields=['student', 'test'], name='cbt_recipient_student_idx'),
        ),
        migrations.AddConstraint(
            model_name='cbtrecipient',
            constraint=models.UniqueConstraint(fields=('test', 'student'), name='cbt_recipient_uq'),
        ),
        migrations.AddConstraint(
            model_name='cbtquestion',
            constraint=models.UniqueConstraint(fields=('test', 'sequence'), name='cbt_question_seq_uq'),
        ),
        migrations.AddConstraint(
            model_name='cbtevent',
            constraint=models.UniqueConstraint(fields=('test', 'revision'), name='cbt_event_revision_uq'),
        ),
        migrations.AddIndex(
            model_name='cbtattempt',
            index=models.Index(fields=['test', 'student'], name='cbt_attempt_test_student_idx'),
        ),
        migrations.AddConstraint(
            model_name='cbtattempt',
            constraint=models.UniqueConstraint(fields=('school', 'external_id'), name='cbt_attempt_external_uq'),
        ),
        migrations.AddConstraint(
            model_name='cbtattempt',
            constraint=models.UniqueConstraint(fields=('test', 'student'), name='cbt_attempt_student_uq'),
        ),
    ]
