# Generated by Django 5.2.17 on 2026-09-25 20:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0005_school_organization_type_location'),
        ('students', '0004_alter_studentregistration_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=40)),
                ('connection_type', models.CharField(choices=[('direct_bank_api', 'Direct bank API'), ('open_banking', 'Open banking'), ('collection_provider', 'Collection provider'), ('sandbox', 'Sandbox')], max_length=24)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('account_mask', models.CharField(blank=True, max_length=16)),
                ('account_fingerprint', models.CharField(blank=True, max_length=64)),
                ('purpose', models.CharField(choices=[('tuition', 'Tuition'), ('transport', 'Transport'), ('books', 'Books'), ('uniforms', 'Uniforms'), ('capital', 'Capital projects'), ('general', 'General collections'), ('other', 'Other')], default='general', max_length=16)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('disabled', 'Disabled'), ('needs_reauth', 'Needs re-authorisation'), ('error', 'Error'), ('revoked', 'Disconnected')], default='pending', max_length=16)),
                ('sealed_credentials', models.BinaryField(blank=True, default=b'')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_token_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('sync_cursor', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=40)),
                ('provider_meta', models.JSONField(blank=True, default=dict)),
                ('is_sandbox', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_connections', to='schools.school')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=32)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='bankconnect.bankconnection')),
            ],
            options={
                'ordering': ['-at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=40)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('bank_account_name', models.CharField(blank=True, max_length=200)),
                ('masked_account_number', models.CharField(blank=True, max_length=16)),
                ('external_transaction_id', models.CharField(max_length=160)),
                ('transaction_reference', models.CharField(blank=True, max_length=160)),
                ('provider_session_id', models.CharField(blank=True, max_length=160)),
                ('transaction_type', models.CharField(blank=True, max_length=40)),
                ('direction', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=8)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('sender_name', models.CharField(blank=True, max_length=200)),
                ('sender_account_mask', models.CharField(blank=True, max_length=16)),
                ('sender_bank', models.CharField(blank=True, max_length=120)),
                ('narration', models.CharField(blank=True, max_length=500)),
                ('transaction_date', models.DateTimeField()),
                ('value_date', models.DateField(blank=True, null=True)),
                ('balance_after_minor', models.BigIntegerField(blank=True, null=True)),
                ('raw_provider_reference', models.CharField(blank=True, max_length=200)),
                ('is_sandbox', models.BooleanField(default=False)),
                ('reconciliation_status', models.CharField(choices=[('matched', 'Matched'), ('partially_matched', 'Partially matched'), ('possible_match', 'Possible match'), ('unmatched', 'Unmatched'), ('duplicate', 'Duplicate'), ('reversed', 'Reversed'), ('refunded', 'Refunded'), ('requires_review', 'Requires review'), ('unrelated_income', 'Unrelated income'), ('investigating', 'Under investigation')], default='unmatched', max_length=20)),
                ('reconciliation_confidence', models.PositiveSmallIntegerField(default=0)),
                ('match_reasons', models.JSONField(blank=True, default=list)),
                ('engine_version', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='bankconnect.bankconnection')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='bankconnect.banktransaction')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to='schools.school')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=40)),
                ('payload_hash', models.CharField(max_length=64)),
                ('signature_valid', models.BooleanField(default=False)),
                ('outcome', models.CharField(blank=True, max_length=24)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bankconnect.bankconnection')),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=24)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='bankconnect.banktransaction')),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SandboxFeedItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sandbox_feed', to='bankconnect.bankconnection')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TransactionAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('tuition', 'Tuition'), ('transport', 'Transport'), ('books', 'Books'), ('uniforms', 'Uniforms'), ('capital', 'Capital projects'), ('general', 'General collections'), ('other', 'Other')], max_length=16)),
                ('amount_minor', models.BigIntegerField()),
                ('source', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], max_length=8)),
                ('receivable_ref', models.CharField(blank=True, max_length=80)),
                ('superseded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bankconnect.reconciliationdecision')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_allocations', to='students.student')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='bankconnect.banktransaction')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bankconnection',
            index=models.Index(fields=['school', 'status'], name='bankconnect_school__8276aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='bankconnection',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('account_fingerprint', ''), _negated=True), models.Q(('status', 'revoked'), _negated=True)), fields=('school', 'provider', 'account_fingerprint'), name='unique_live_bank_account_per_school'),
        ),
        migrations.AddIndex(
            model_name='bankauditevent',
            index=models.Index(fields=['school', '-at'], name='bankconnect_school__b6c676_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['school', '-transaction_date'], name='bankconnect_school__6278e0_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['school', 'reconciliation_status'], name='bankconnect_school__d49bd9_idx'),
        ),
        migrations.AddConstraint(
            model_name='banktransaction',
            constraint=models.UniqueConstraint(fields=('connection', 'external_transaction_id'), name='unique_transaction_per_connection'),
        ),
        migrations.AddConstraint(
            model_name='banktransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_session_id', ''), _negated=True), fields=('school', 'provider', 'provider_session_id'), name='unique_provider_session_per_school'),
        ),
        migrations.AddConstraint(
            model_name='banktransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='bank_transaction_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='bankwebhookevent',
            constraint=models.UniqueConstraint(fields=('provider', 'payload_hash'), name='unique_bank_webhook_payload'),
        ),
        migrations.AddConstraint(
            model_name='transactionallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='allocation_amount_positive'),
        ),
    ]
