# Generated by Django 5.2.17 on 2026-09-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankconnect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='reconciliation_status',
            field=models.CharField(choices=[('matched', 'Matched'), ('partially_matched', 'Partially matched'), ('possible_match', 'Possible match'), ('unmatched', 'Unmatched'), ('duplicate', 'Duplicate'), ('reversed', 'Reversed'), ('refunded', 'Refunded'), ('requires_review', 'Requires review'), ('unrelated_income', 'Unrelated income'), ('investigating', 'Under investigation'), ('not_applicable', 'Not applicable')], default='unmatched', max_length=20),
        ),
    ]
