# Generated by Django 5.2.17 on 2026-09-26 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankconnect', '0002_transaction_not_applicable_status'),
        ('receivables', '0002_fees_receivables_adjustments'),
        ('schools', '0005_school_organization_type_location'),
        ('students', '0003_student_guardian_account_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_transactions', to='receivables.family'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='receiving_account_ref',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='receivables.family'),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='receivable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='receivables.studentreceivable'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['school', 'provider', 'receiving_account_ref'], name='bankconnect_school__039f04_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionallocation',
            index=models.Index(fields=['receivable', 'superseded'], name='bankconnect_receiva_1dc9bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='transactionallocation',
            constraint=models.CheckConstraint(condition=models.Q(('receivable__isnull', True), ('family__isnull', False), _connector='OR'), name='receivable_allocation_has_a_family'),
        ),
    ]
