# Generated by Django 5.2.17 on 2026-09-25 10:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0005_school_organization_type_location'),
        ('students', '0003_student_guardian_account_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadDebtClassification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('outstanding', 'Outstanding'), ('recovery_in_progress', 'Recovery in progress'), ('bad_debt', 'Bad debt / unresolved obligation'), ('resolved', 'Resolved')], default='outstanding', max_length=24)),
                ('outstanding_amount_minor', models.PositiveIntegerField()),
                ('current_canonical_balance_minor', models.PositiveIntegerField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('evidence_reference', models.CharField(blank=True, max_length=200)),
                ('classified_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classified_bad_debts', to='schools.membership')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_bad_debts', to='schools.membership')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_bad_debts', to='schools.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bad_debt_classifications', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bad_debt_classifications', to='students.student')),
            ],
            options={
                'ordering': ['-classified_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BadDebtEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=32)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bad_debt_events', to='schools.membership')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='transferverify.baddebtclassification')),
            ],
            options={
                'ordering': ['-revision'],
            },
        ),
        migrations.AddIndex(
            model_name='baddebtclassification',
            index=models.Index(fields=['school', 'status'], name='bad_debt_school_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='baddebtclassification',
            constraint=models.UniqueConstraint(fields=('school', 'external_id'), name='bad_debt_external_uq'),
        ),
        migrations.AddConstraint(
            model_name='baddebtclassification',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['outstanding', 'recovery_in_progress', 'bad_debt'])), fields=('student',), name='bad_debt_one_open_per_student'),
        ),
        migrations.AddConstraint(
            model_name='baddebtevent',
            constraint=models.UniqueConstraint(fields=('classification', 'revision'), name='bad_debt_event_revision_uq'),
        ),
    ]
