# Generated by Django 5.2.17 on 2026-09-25 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_school_organization_type_location'),
        ('transferverify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baddebtclassification',
            name='association_scope',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='baddebtclassification',
            name='publication_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='baddebtclassification',
            name='publication_reason',
            field=models.CharField(blank=True, choices=[('withdrew_without_clearance', 'Withdrew without financial clearance'), ('guardian_unreachable', 'Guardian unreachable after recovery attempts'), ('arrangement_defaulted', 'Payment arrangement defaulted'), ('unresolved_after_withdrawal', 'Unresolved balance after withdrawal'), ('transfer_suspected', 'Transfer suspected while balance remains'), ('other', 'Other documented reason')], max_length=32),
        ),
        migrations.AddField(
            model_name='baddebtclassification',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baddebtclassification',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_bad_debts', to='schools.membership'),
        ),
    ]
