# Generated by Django 5.2.17 on 2026-09-25 12:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_school_organization_type_location'),
        ('transferverify', '0002_baddebtclassification_association_scope_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProprietorAssociation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('registration_reference', models.CharField(blank=True, max_length=200)),
                ('geographic_scope', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending_verification', 'Pending verification'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending_verification', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssociationAdministrator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='association_administrator_roles', to=settings.AUTH_USER_MODEL)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to='transferverify.schoolproprietorassociation')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolAssociationMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('exited', 'Exited')], default='pending', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_memberships', to='transferverify.associationadministrator')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_association_memberships', to='schools.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='association_memberships', to='schools.school')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_memberships', to='transferverify.schoolproprietorassociation')),
            ],
            options={
                'ordering': ['-requested_at'],
                'constraints': [models.UniqueConstraint(fields=('association', 'school'), name='one_membership_per_school_per_association')],
            },
        ),
        migrations.AddConstraint(
            model_name='associationadministrator',
            constraint=models.UniqueConstraint(fields=('association', 'user'), name='one_admin_link_per_user_per_association'),
        ),
    ]
