# Generated by Django 5.2.17 on 2026-09-25 12:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_school_organization_type_location'),
        ('students', '0003_student_guardian_account_links'),
        ('transferverify', '0003_schoolproprietorassociation_associationadministrator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkStudentIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkSearchAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_count', models.PositiveIntegerField()),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('searching_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='network_searches', to='schools.membership')),
                ('searching_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_searches', to='schools.school')),
            ],
            options={
                'ordering': ['-searched_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentNetworkEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guardian_phone_e164', models.CharField(blank=True, db_index=True, max_length=20)),
                ('guardian_phone_history', models.JSONField(blank=True, default=list)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linked_network_enrollments', to='schools.membership')),
                ('network_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='transferverify.networkstudentidentity')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_enrollments', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_enrollments', to='students.student')),
            ],
            options={
                'indexes': [models.Index(fields=['guardian_phone_e164'], name='network_enrollment_phone_idx')],
                'constraints': [models.UniqueConstraint(fields=('network_identity', 'school'), name='enrollment_identity_school_uq'), models.UniqueConstraint(fields=('school', 'student'), name='enrollment_student_school_uq')],
            },
        ),
        migrations.CreateModel(
            name='TransferAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('association_scope', models.JSONField(blank=True, default=list)),
                ('state', models.CharField(choices=[('active', 'Active'), ('verification_pending', 'Verification pending'), ('disputed', 'Disputed'), ('resolved', 'Resolved'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='active', max_length=24)),
                ('snapshot_status', models.CharField(max_length=24)),
                ('snapshot_outstanding_amount_minor', models.PositiveIntegerField()),
                ('snapshot_reason', models.CharField(blank=True, max_length=32)),
                ('snapshot_note', models.TextField(blank=True)),
                ('published_at', models.DateTimeField()),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network_identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_alerts', to='transferverify.networkstudentidentity')),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_transfer_alerts', to='schools.membership')),
                ('source_classification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_alert', to='transferverify.baddebtclassification')),
                ('source_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_transfer_alerts', to='schools.school')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['network_identity', 'state'], name='tv_alert_identity_state_idx')],
            },
        ),
    ]
