# Generated by Django 5.2.17 on 2026-09-25 12:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_school_organization_type_location'),
        ('transferverify', '0004_networkstudentidentity_networksearchaudit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferVerificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_note', models.TextField(blank=True)),
                ('response_status_snapshot', models.CharField(blank=True, max_length=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_verification_requests', to='schools.membership')),
                ('requesting_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_verification_requests', to='schools.school')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_verification_requests', to='schools.membership')),
                ('transfer_alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='transferverify.transferalert')),
            ],
            options={
                'ordering': ['-requested_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('transfer_alert', 'requesting_school'), name='one_pending_request_per_alert_school')],
            },
        ),
    ]
