# Generated by Django 5.2.17 on 2026-09-25 13:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_school_organization_type_location'),
        ('students', '0003_student_guardian_account_links'),
        ('transferverify', '0005_transferverificationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('granted', 'Granted'), ('withdrawn', 'Withdrawn')], default='granted', max_length=16)),
                ('guardian_name', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_biometric_consents', to='schools.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_consents', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_consents', to='students.student')),
                ('withdrawn_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawn_biometric_consents', to='schools.membership')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentBiometricTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finger', models.CharField(choices=[('right_thumb', 'Right thumb'), ('right_index', 'Right index'), ('right_middle', 'Right middle'), ('right_ring', 'Right ring'), ('right_little', 'Right little'), ('left_thumb', 'Left thumb'), ('left_index', 'Left index'), ('left_middle', 'Left middle'), ('left_ring', 'Left ring'), ('left_little', 'Left little'), ('other', 'Other')], max_length=16)),
                ('template_data', models.BinaryField()),
                ('template_version', models.CharField(max_length=40)),
                ('quality_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source_device', models.CharField(blank=True, max_length=120)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('captured_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='captured_biometric_templates', to='schools.membership')),
                ('consent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='transferverify.biometricconsent')),
                ('enrolled_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_biometric_templates', to='schools.school')),
                ('network_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_templates', to='transferverify.networkstudentidentity')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_biometric_templates', to='schools.membership')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='biometricconsent',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'granted')), fields=('school', 'student'), name='one_active_consent_per_student_school'),
        ),
        migrations.AddIndex(
            model_name='studentbiometrictemplate',
            index=models.Index(fields=['network_identity'], name='biometric_tpl_identity_idx'),
        ),
    ]
