# Generated by Django 5.2.17 on 2026-09-25 13:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_school_organization_type_location'),
        ('transferverify', '0006_biometricconsent_studentbiometrictemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferClearance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_token', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_clearances', to='schools.membership')),
                ('issuing_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_clearances', to='schools.school')),
                ('network_identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clearances', to='transferverify.networkstudentidentity')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_clearances', to='schools.membership')),
                ('source_alert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clearances', to='transferverify.transferalert')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferClearanceDispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('not_the_same_family', 'This is not our family'), ('already_paid', 'The balance has already been paid'), ('amount_disputed', 'The amount is incorrect'), ('never_enrolled_here', 'This student was never enrolled at that school'), ('arrangement_honored', 'A payment arrangement is being honored'), ('other', 'Other documented reason')], max_length=32)),
                ('explanation', models.TextField(blank=True)),
                ('evidence_references', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('opened', 'Opened'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='opened', max_length=16)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_transfer_disputes', to='schools.membership')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_transfer_disputes', to='schools.membership')),
                ('transfer_alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='transferverify.transferalert')),
            ],
            options={
                'ordering': ['-opened_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'opened')), fields=('transfer_alert',), name='one_open_dispute_per_alert')],
            },
        ),
    ]
