# Generated by Django 5.2.17 on 2026-09-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferverify', '0007_transferclearance_transferclearancedispute'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferalert',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
