# Generated by Django 5.2.17 on 2026-09-24 22:14

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_elective_selection_history'),
        ('schools', '0005_school_organization_type_location'),
        ('students', '0003_student_guardian_account_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=128)),
                ('assessment_type', models.CharField(choices=[('ca', 'Continuous Assessment'), ('quiz', 'Quiz'), ('test', 'Test'), ('exam', 'Exam'), ('practical', 'Practical'), ('project', 'Project')], default='ca', max_length=16)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('submitted', 'Submitted for review'), ('locked', 'Locked'), ('released', 'Released')], default='draft', max_length=16)),
                ('title', models.CharField(blank=True, max_length=240)),
                ('maximum_score', models.PositiveIntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('version', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_assessments', to='schools.membership')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='academics.classsubject')),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edited_assessments', to='schools.membership')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locked_assessments', to='schools.membership')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='released_assessments', to='schools.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_assessments', to='schools.school')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_assessments', to='schools.membership')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='academics.academicterm')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=24)),
                ('comment', models.TextField(blank=True)),
                ('previous_score', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('new_score', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_events', to='schools.membership')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='assessments.assessmentdefinition')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='students.student')),
            ],
            options={
                'ordering': ['-revision'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_code', models.CharField(max_length=80)),
                ('student_name', models.CharField(max_length=320)),
                ('admission_number', models.CharField(blank=True, max_length=80)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipients', to='assessments.assessmentdefinition')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_recipients', to='students.student')),
            ],
            options={
                'ordering': ['student_name', 'student_code'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('entered_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='assessments.assessmentdefinition')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='schools.membership')),
                ('recipient', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='score', to='assessments.assessmentrecipient')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_scores', to='students.student')),
            ],
            options={
                'ordering': ['student__surname', 'student__first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='assessmentdefinition',
            index=models.Index(fields=['school', 'state'], name='assess_school_state_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentdefinition',
            index=models.Index(fields=['class_subject', 'term', 'state'], name='assess_subject_term_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentdefinition',
            constraint=models.UniqueConstraint(fields=('school', 'external_id'), name='assess_external_uq'),
        ),
        migrations.AddConstraint(
            model_name='assessmentevent',
            constraint=models.UniqueConstraint(fields=('assessment', 'revision'), name='assess_event_revision_uq'),
        ),
        migrations.AddIndex(
            model_name='assessmentrecipient',
            index=models.Index(fields=['student', 'assessment'], name='assess_student_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentrecipient',
            constraint=models.UniqueConstraint(fields=('assessment', 'student'), name='assess_recipient_uq'),
        ),
        migrations.AddIndex(
            model_name='assessmentscore',
            index=models.Index(fields=['student', 'assessment'], name='assess_score_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentscore',
            constraint=models.UniqueConstraint(fields=('assessment', 'student'), name='assess_score_student_uq'),
        ),
    ]
