"""Mandates & Direct Debit: the school's own Remita / Lendsqr connections (no "active provider"), payers' mandates with explicit consent, maker-checker debit
batches, the debits themselves and their provider job queue, and the development sandbox provider. Separate from Smart Money Collection."""

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_alter_studentsubjectselection_options'),
        ('bankconnect', '0007_mandates_and_direct_debit'),
        ('receivables', '0007_collection_account_reuse_and_grace'),
        ('schools', '0005_school_organization_type_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectDebitMandate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=40)),
                ('environment', models.CharField(max_length=8)),
                ('provider_mandate_reference', models.CharField(blank=True, max_length=120)),
                ('mandate_code', models.CharField(blank=True, max_length=120)),
                ('provider_customer_ref', models.CharField(blank=True, max_length=60)),
                ('request_ref', models.CharField(max_length=40)),
                ('bank_code', models.CharField(max_length=12)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('account_mask', models.CharField(max_length=16)),
                ('account_fingerprint', models.CharField(max_length=64)),
                ('sealed_account_details', models.BinaryField(blank=True, default=b'')),
                ('account_details_removed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_consent', "Waiting for the payer's authorisation"), ('pending_activation', 'Waiting for the payer to activate it'), ('activating', 'Being activated'), ('pending_provider_setup', 'Waiting for the provider to finish setting it up'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('failed', 'Failed')], default='draft', max_length=24)),
                ('provider_status', models.CharField(blank=True, max_length=120)),
                ('provider_status_code', models.CharField(blank=True, max_length=20)),
                ('consent_route', models.CharField(choices=[('payer_app', 'In the SchoolOS app'), ('provider', 'With the provider')], default='payer_app', max_length=10)),
                ('maximum_amount_minor', models.BigIntegerField(blank=True, null=True)),
                ('max_debits', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('consent_channel', models.CharField(blank=True, choices=[('payer_app', 'Authorised by the payer in the app'), ('provider_hosted', 'Authorised with the provider')], max_length=16)),
                ('consent_version', models.CharField(blank=True, max_length=20)),
                ('consent_reference', models.CharField(blank=True, max_length=120)),
                ('activation_started_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('debit_ready_at', models.DateTimeField(blank=True, null=True)),
                ('activation_deadline', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('activation_details', models.JSONField(blank=True, default=dict)),
                ('failure_code', models.CharField(blank=True, max_length=40)),
                ('provider_meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_debit_mandates', to='receivables.family')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_debit_mandates', to='receivables.familyguardian')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_debit_mandates', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MandateDebitBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Waiting for approval'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('processing', 'Debiting'), ('partially_successful', 'Completed with failures'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('snapshot_hash', models.CharField(blank=True, max_length=64)),
                ('approved_snapshot_hash', models.CharField(blank=True, max_length=64)),
                ('approved_version', models.PositiveIntegerField(blank=True, null=True)),
                ('prepared_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=500)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('family_count', models.PositiveIntegerField(default=0)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('total_outstanding_minor', models.BigIntegerField(default=0)),
                ('total_amount_minor', models.BigIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('preview_built_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandate_debit_batches', to='schools.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.academicsession')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.academicterm')),
            ],
            options={
                'ordering': ['-prepared_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MandateBatchEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='mandates.mandatedebitbatch')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MandateEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=32)),
                ('from_status', models.CharField(blank=True, max_length=24)),
                ('to_status', models.CharField(blank=True, max_length=24)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
                ('mandate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='mandates.directdebitmandate')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MandateProviderConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=40)),
                ('environment', models.CharField(choices=[('live', 'Live'), ('test', 'Test')], default='live', max_length=8)),
                ('merchant_name', models.CharField(blank=True, max_length=200)),
                ('merchant_reference', models.CharField(blank=True, max_length=60)),
                ('provider_settings', models.JSONField(blank=True, default=dict)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('disabled', 'Disabled'), ('needs_reauth', 'Needs re-authorisation'), ('error', 'Error'), ('revoked', 'Disconnected')], default='pending', max_length=16)),
                ('sealed_credentials', models.BinaryField(blank=True, default=b'')),
                ('webhook_token_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('webhook_status', models.CharField(choices=[('not_configured', 'Not set up'), ('awaiting_event', 'Waiting for the first event'), ('active', 'Active')], default='not_configured', max_length=16)),
                ('webhook_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=40)),
                ('provider_meta', models.JSONField(blank=True, default=dict)),
                ('is_sandbox', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandate_connections', to='schools.school')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MandateDebitInstruction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('mandate_status', models.CharField(blank=True, max_length=24)),
                ('selected', models.BooleanField(default=False)),
                ('outstanding_minor', models.BigIntegerField(default=0)),
                ('eligible_minor', models.BigIntegerField(default=0)),
                ('maximum_minor', models.BigIntegerField(blank=True, null=True)),
                ('proposed_debit_minor', models.BigIntegerField(default=0)),
                ('amount_adjusted', models.BooleanField(default=False)),
                ('receivable_allocation', models.JSONField(blank=True, default=list)),
                ('eligibility_status', models.CharField(choices=[('eligible', 'Ready to debit'), ('no_mandate', 'No mandate'), ('not_ready', 'Mandate not ready'), ('nothing_due', 'Nothing to collect'), ('provider_unavailable', 'Provider not working'), ('provider_cannot_debit', 'Provider cannot debit yet')], default='eligible', max_length=24)),
                ('eligibility_note', models.CharField(blank=True, max_length=300)),
                ('fingerprint', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Waiting'), ('skipped', 'Not selected'), ('debiting', 'Being debited'), ('unknown', 'Outcome not yet known'), ('success', 'Debited'), ('failed', 'Failed'), ('retrying', 'Trying again'), ('cancelled', 'Cancelled')], default='skipped', max_length=12)),
                ('idempotency_key', models.CharField(blank=True, max_length=80)),
                ('request_ref', models.CharField(blank=True, max_length=40)),
                ('retry_round', models.PositiveSmallIntegerField(default=0)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('provider_transaction_reference', models.CharField(blank=True, max_length=120)),
                ('provider_status', models.CharField(blank=True, max_length=120)),
                ('provider_status_code', models.CharField(blank=True, max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('safe_error_message', models.CharField(blank=True, max_length=300)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='mandates.mandatedebitbatch')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='receivables.family')),
                ('mandate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debit_items', to='mandates.directdebitmandate')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='receivables.familyguardian')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
                ('provider_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mandates.mandateproviderconnection')),
            ],
            options={
                'ordering': ['family__display_name', 'family__code'],
            },
        ),
        migrations.AddField(
            model_name='directdebitmandate',
            name='provider_connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mandates', to='mandates.mandateproviderconnection'),
        ),
        migrations.CreateModel(
            name='MandateProviderEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=40)),
                ('payload_hash', models.CharField(max_length=64)),
                ('authenticity_valid', models.BooleanField(default=False)),
                ('event_type', models.CharField(blank=True, max_length=24)),
                ('outcome', models.CharField(blank=True, max_length=24)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mandates.mandateproviderconnection')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='MandateProviderJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('debit', 'Send a debit instruction'), ('requery', 'Ask the provider what happened to a debit')], max_length=10)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('retry', 'Waiting to retry'), ('succeeded', 'Done'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('run_after', models.DateTimeField()),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='mandates.mandatedebitinstruction')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
            ],
            options={
                'ordering': ['run_after', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MandateTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=40)),
                ('request_ref', models.CharField(max_length=40)),
                ('provider_transaction_reference', models.CharField(blank=True, max_length=120)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Successful'), ('failed', 'Failed'), ('reversed', 'Reversed'), ('refunded', 'Refunded'), ('unknown', 'Unknown'), ('not_found', 'Not found')], default='pending', max_length=10)),
                ('provider_status', models.CharField(blank=True, max_length=120)),
                ('provider_status_code', models.CharField(blank=True, max_length=20)),
                ('failure_code', models.CharField(blank=True, max_length=40)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('provider_meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='receivables.family')),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='mandates.mandatedebitinstruction')),
                ('mandate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='mandates.directdebitmandate')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='receivables.familyguardian')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mandate_transaction', to='bankconnect.banktransaction')),
                ('provider_connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mandates.mandateproviderconnection')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandate_transactions', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SandboxDebit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mandate_ref', models.CharField(max_length=60)),
                ('request_ref', models.CharField(max_length=40)),
                ('provider_reference', models.CharField(max_length=60, unique=True)),
                ('amount_minor', models.BigIntegerField()),
                ('status', models.CharField(default='success', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mandates.mandateproviderconnection')),
            ],
        ),
        migrations.CreateModel(
            name='SandboxMandate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_ref', models.CharField(max_length=60, unique=True)),
                ('request_ref', models.CharField(max_length=40)),
                ('bank_code', models.CharField(max_length=12)),
                ('account_mask', models.CharField(blank=True, max_length=16)),
                ('maximum_minor', models.BigIntegerField()),
                ('status', models.CharField(default='pending_activation', max_length=24)),
                ('challenge_ref', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debit_ready_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mandates.mandateproviderconnection')),
            ],
        ),
        migrations.CreateModel(
            name='MandateAuditEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=40)),
                ('object_type', models.CharField(max_length=40)),
                ('object_id', models.CharField(max_length=64)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['school', '-at'], name='mandates_ma_school__f6425f_idx'), models.Index(fields=['school', 'object_type', 'object_id'], name='mandates_ma_school__7c863c_idx')],
            },
        ),
        migrations.CreateModel(
            name='MandateConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_version', models.CharField(max_length=20)),
                ('consent_text_hash', models.CharField(blank=True, max_length=64)),
                ('channel', models.CharField(choices=[('payer_app', 'Authorised by the payer in the app'), ('provider_hosted', 'Authorised with the provider')], max_length=16)),
                ('consented_at', models.DateTimeField()),
                ('provider_consent_reference', models.CharField(blank=True, max_length=120)),
                ('safe_evidence_reference', models.CharField(blank=True, max_length=120)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mandate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='mandates.directdebitmandate')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mandate_consents', to='receivables.familyguardian')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
            ],
            options={
                'ordering': ['consented_at', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('withdrawn_at__isnull', True)), fields=('mandate',), name='one_standing_consent_per_mandate'), models.CheckConstraint(condition=models.Q(models.Q(('channel', 'payer_app'), _negated=True), models.Q(models.Q(('consent_text_hash', ''), _negated=True), ('recorded_by__isnull', False)), _connector='OR'), name='app_consent_names_the_words_and_the_payer')],
            },
        ),
        migrations.AddIndex(
            model_name='mandatedebitbatch',
            index=models.Index(fields=['school', 'status'], name='mandates_ma_school__070444_idx'),
        ),
        migrations.AddIndex(
            model_name='mandatedebitbatch',
            index=models.Index(fields=['school', '-prepared_at'], name='mandates_ma_school__494b32_idx'),
        ),
        migrations.AddConstraint(
            model_name='mandatedebitbatch',
            constraint=models.CheckConstraint(condition=models.Q(('approved_by', models.F('prepared_by')), _negated=True), name='debit_checker_is_not_the_preparer'),
        ),
        migrations.AddConstraint(
            model_name='mandatedebitbatch',
            constraint=models.CheckConstraint(condition=models.Q(('approved_by', models.F('submitted_by')), _negated=True), name='debit_checker_is_not_the_submitter'),
        ),
        migrations.AddConstraint(
            model_name='mandatedebitbatch',
            constraint=models.CheckConstraint(condition=models.Q(('rejected_by__isnull', True), models.Q(('rejection_reason', ''), _negated=True), _connector='OR'), name='a_debit_rejection_has_a_reason'),
        ),
        migrations.AddConstraint(
            model_name='mandatedebitbatch',
            constraint=models.CheckConstraint(condition=models.Q(('approved_by__isnull', True), models.Q(models.Q(('approved_snapshot_hash', ''), _negated=True), ('approved_version__isnull', False)), _connector='OR'), name='a_debit_approval_is_for_a_snapshot'),
        ),
        migrations.AddIndex(
            model_name='mandateproviderconnection',
            index=models.Index(fields=['school', 'status'], name='mandates_ma_school__3f0b17_idx'),
        ),
        migrations.AddConstraint(
            model_name='mandateproviderconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'revoked'), _negated=True), fields=('school', 'provider'), name='one_live_mandate_connection_per_provider'),
        ),
        migrations.AddConstraint(
            model_name='mandateproviderconnection',
            constraint=models.CheckConstraint(condition=models.Q(('provider__in', ('remita', 'lendsqr', 'sandbox'))), name='mandate_connection_is_a_mandate_provider'),
        ),
        migrations.AddIndex(
            model_name='mandatedebitinstruction',
            index=models.Index(fields=['batch', 'status'], name='mandates_ma_batch_i_5402a0_idx'),
        ),
        migrations.AddIndex(
            model_name='mandatedebitinstruction',
            index=models.Index(fields=['batch', 'eligibility_status'], name='mandates_ma_batch_i_3f7aab_idx'),
        ),
        migrations.AddConstraint(
            model_name='mandatedebitinstruction',
            constraint=models.UniqueConstraint(fields=('batch', 'family'), name='one_debit_item_per_family_per_batch'),
        ),
        migrations.AddConstraint(
            model_name='mandatedebitinstruction',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('school', 'idempotency_key'), name='one_debit_item_per_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='mandatedebitinstruction',
            constraint=models.UniqueConstraint(condition=models.Q(('request_ref', ''), _negated=True), fields=('provider_connection', 'request_ref'), name='one_debit_item_per_provider_request'),
        ),
        migrations.AddConstraint(
            model_name='mandatedebitinstruction',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_transaction_reference', ''), _negated=True), fields=('provider_connection', 'provider_transaction_reference'), name='one_debit_item_per_provider_transaction'),
        ),
        migrations.AddConstraint(
            model_name='mandatedebitinstruction',
            constraint=models.CheckConstraint(condition=models.Q(('selected', False), ('mandate__isnull', False), _connector='OR'), name='a_selected_debit_has_a_mandate'),
        ),
        migrations.AddConstraint(
            model_name='mandatedebitinstruction',
            constraint=models.CheckConstraint(condition=models.Q(('proposed_debit_minor__gte', 0), ('proposed_debit_minor__lte', models.F('eligible_minor'))), name='a_debit_never_exceeds_what_is_owed'),
        ),
        migrations.AddConstraint(
            model_name='mandatedebitinstruction',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_minor__isnull', True), ('proposed_debit_minor__lte', models.F('maximum_minor')), _connector='OR'), name='a_debit_never_exceeds_the_mandate_limit'),
        ),
        migrations.AddConstraint(
            model_name='mandatedebitinstruction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'success'), _negated=True), models.Q(models.Q(('request_ref', ''), _negated=True), ('proposed_debit_minor__gt', 0)), _connector='OR'), name='a_successful_debit_has_a_reference_and_an_amount'),
        ),
        migrations.AddIndex(
            model_name='directdebitmandate',
            index=models.Index(fields=['school', 'status'], name='mandates_di_school__8bb304_idx'),
        ),
        migrations.AddIndex(
            model_name='directdebitmandate',
            index=models.Index(fields=['school', 'family', 'status'], name='mandates_di_school__30a1b8_idx'),
        ),
        migrations.AddIndex(
            model_name='directdebitmandate',
            index=models.Index(fields=['school', 'account_fingerprint'], name='mandates_di_school__c90f67_idx'),
        ),
        migrations.AddConstraint(
            model_name='directdebitmandate',
            constraint=models.UniqueConstraint(fields=('school', 'request_ref'), name='one_mandate_per_setup_request'),
        ),
        migrations.AddConstraint(
            model_name='directdebitmandate',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_mandate_reference', ''), _negated=True), fields=('provider_connection', 'provider_mandate_reference'), name='one_mandate_per_provider_reference'),
        ),
        migrations.AddConstraint(
            model_name='directdebitmandate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('status__in', ('draft', 'pending_consent', 'pending_activation', 'activating', 'pending_provider_setup', 'active', 'suspended'))), fields=('family',), name='one_primary_mandate_per_family'),
        ),
        migrations.AddConstraint(
            model_name='directdebitmandate',
            constraint=models.CheckConstraint(condition=models.Q(('is_primary', False), models.Q(('status__in', ('cancelled', 'expired', 'failed')), _negated=True), _connector='OR'), name='an_ended_mandate_is_not_primary'),
        ),
        migrations.AddConstraint(
            model_name='directdebitmandate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['active', 'pending_provider_setup', 'activating']), _negated=True), ('consent_at__isnull', False), _connector='OR'), name='a_usable_mandate_has_consent'),
        ),
        migrations.AddConstraint(
            model_name='directdebitmandate',
            constraint=models.CheckConstraint(condition=models.Q(('provider__in', ('remita', 'lendsqr', 'sandbox'))), name='mandate_is_with_a_mandate_provider'),
        ),
        migrations.AddConstraint(
            model_name='mandateproviderevent',
            constraint=models.UniqueConstraint(fields=('provider', 'payload_hash'), name='unique_mandate_provider_event'),
        ),
        migrations.AddIndex(
            model_name='mandateproviderjob',
            index=models.Index(fields=['status', 'run_after'], name='mandates_ma_status_7b9846_idx'),
        ),
        migrations.AddIndex(
            model_name='mandatetransaction',
            index=models.Index(fields=['school', 'status'], name='mandates_ma_school__e7f47d_idx'),
        ),
        migrations.AddIndex(
            model_name='mandatetransaction',
            index=models.Index(fields=['school', 'family'], name='mandates_ma_school__a3fb8d_idx'),
        ),
        migrations.AddConstraint(
            model_name='mandatetransaction',
            constraint=models.UniqueConstraint(fields=('provider_connection', 'request_ref'), name='one_mandate_transaction_per_request'),
        ),
        migrations.AddConstraint(
            model_name='mandatetransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_transaction_reference', ''), _negated=True), fields=('provider_connection', 'provider_transaction_reference'), name='one_mandate_transaction_per_provider_reference'),
        ),
        migrations.AddConstraint(
            model_name='mandatetransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='mandate_transaction_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='mandatetransaction',
            constraint=models.CheckConstraint(condition=models.Q(('payment__isnull', True), ('status__in', ['success', 'reversed', 'refunded']), _connector='OR'), name='only_a_confirmed_debit_is_a_payment'),
        ),
        migrations.AddConstraint(
            model_name='sandboxdebit',
            constraint=models.UniqueConstraint(fields=('connection', 'request_ref'), name='sandbox_debit_once_per_request'),
        ),
        migrations.AddConstraint(
            model_name='sandboxmandate',
            constraint=models.UniqueConstraint(fields=('connection', 'request_ref'), name='sandbox_mandate_once_per_request'),
        ),
    ]
