# Generated by Django 5.2.17 on 2026-09-20 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutation_id', models.CharField(max_length=64)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.CharField(max_length=128)),
                ('operation', models.CharField(max_length=10)),
                ('disposition', models.CharField(max_length=10)),
                ('server_version', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='schools.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutation_logs', to='schools.school')),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'entity_type', 'entity_id'], name='sync_mutati_school__e5977a_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'mutation_id'), name='unique_mutation_id')],
            },
        ),
        migrations.CreateModel(
            name='SyncRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.CharField(max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_records', to='schools.school')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'entity_type'], name='sync_syncre_school__90415f_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'entity_type', 'entity_id'), name='unique_sync_record')],
            },
        ),
    ]
