# Generated by Django 5.2.17 on 2026-09-29 09:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0005_school_organization_type_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(max_length=64)),
                ('owner_id', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=64)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('stored_filename', models.CharField(max_length=140)),
                ('mime_type', models.CharField(max_length=120)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('generated_document', 'Generated document'), ('other', 'Other')], max_length=20)),
                ('byte_size', models.BigIntegerField()),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('storage_provider', models.CharField(choices=[('local', 'Local disk (development and tests)'), ('s3', 'S3-compatible object storage')], max_length=10)),
                ('storage_key', models.CharField(max_length=512, unique=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('staff', 'Staff'), ('school', 'Everyone at the school'), ('parents', 'Parents'), ('public', 'Public')], default='private', max_length=10)),
                ('status', models.CharField(choices=[('pending_upload', 'Waiting for the upload'), ('uploaded', 'Uploaded'), ('verified', 'Verified'), ('available', 'Available'), ('failed', 'Failed'), ('quarantined', 'Quarantined'), ('retired', 'Retired')], default='pending_upload', max_length=20)),
                ('failure_code', models.CharField(blank=True, max_length=40)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='schools.school')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
            ],
        ),
        migrations.CreateModel(
            name='MediaAuditEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=40)),
                ('object_type', models.CharField(max_length=40)),
                ('object_id', models.CharField(max_length=64)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MediaDerivative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(default='thumbnail', max_length=20)),
                ('storage_provider', models.CharField(choices=[('local', 'Local disk (development and tests)'), ('s3', 'S3-compatible object storage')], max_length=10)),
                ('storage_key', models.CharField(max_length=512, unique=True)),
                ('mime_type', models.CharField(max_length=120)),
                ('byte_size', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivatives', to='schoolos_media.mediaasset')),
            ],
        ),
        migrations.CreateModel(
            name='MediaJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('verify', 'Verify the upload'), ('thumbnail', 'Build a thumbnail'), ('purge', 'Purge retired bytes')], max_length=12)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('retry', 'Waiting to retry'), ('succeeded', 'Done'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('idempotency_key', models.CharField(max_length=140, unique=True)),
                ('run_after', models.DateTimeField()),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='schoolos_media.mediaasset')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
            ],
            options={
                'ordering': ['run_after', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['school', 'owner_type', 'owner_id'], name='schoolos_me_school__dd2a5b_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['school', 'status'], name='schoolos_me_school__386374_idx'),
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'retired'), ('deleted_at__isnull', False)), models.Q(models.Q(('status', 'retired'), _negated=True), ('deleted_at__isnull', True)), _connector='OR'), name='media_asset_retired_matches_deleted_at'),
        ),
        migrations.AddIndex(
            model_name='mediaauditevent',
            index=models.Index(fields=['school', '-at'], name='schoolos_me_school__fde865_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaauditevent',
            index=models.Index(fields=['school', 'object_type', 'object_id'], name='schoolos_me_school__d33719_idx'),
        ),
        migrations.AddConstraint(
            model_name='mediaderivative',
            constraint=models.UniqueConstraint(fields=('asset', 'kind'), name='one_derivative_of_each_kind_per_asset'),
        ),
        migrations.AddIndex(
            model_name='mediajob',
            index=models.Index(fields=['status', 'run_after'], name='schoolos_me_status_ad9f02_idx'),
        ),
    ]
