# Generated by Django 5.2.17 on 2026-09-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='official_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='school',
            name='official_sender_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
