# Generated by Django 5.2.17 on 2026-09-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_official_email_school_official_sender_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('proprietor', 'Proprietor'), ('administrator', 'Administrator'), ('principal', 'Principal'), ('teacher', 'Teacher'), ('accountant', 'Accountant'), ('parent', 'Parent'), ('student', 'Student'), ('staff', 'Staff'), ('driver', 'Driver')], max_length=20),
        ),
    ]
