# Generated by Django 5.2.17 on 2026-09-20 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=24)),
                ('role', models.CharField(blank=True, max_length=20)),
                ('activity', models.CharField(blank=True, max_length=64)),
                ('detail', models.JSONField(default=dict)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_changes', to='schools.school')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
            ],
            options={
                'ordering': ['-at', '-id'],
                'indexes': [models.Index(fields=['school', '-at'], name='access_acce_school__f5869e_idx')],
            },
        ),
        migrations.CreateModel(
            name='MembershipActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=64)),
                ('effect', models.CharField(choices=[('grant', 'Grant'), ('block', 'Block')], max_length=5)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('set_at', models.DateTimeField(auto_now=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_overrides', to='schools.membership')),
                ('set_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.membership')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('membership', 'activity'), name='unique_person_activity')],
            },
        ),
        migrations.CreateModel(
            name='RoleActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('activity', models.CharField(max_length=64)),
                ('enabled', models.BooleanField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_activities', to='schools.school')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('school', 'role', 'activity'), name='unique_role_activity')],
            },
        ),
    ]
