# Generated by Django 5.2.17 on 2026-09-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipactivity',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipactivity',
            name='finalize_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
