"""A collection batch: prepared by a maker, approved by a different checker for exactly the snapshot they saw, and only then run.

    DRAFT -> PENDING_APPROVAL -> APPROVED -> PROCESSING -> COMPLETED | PARTIALLY_SUCCESSFUL | FAILED
                  |                                         (failed families can be retried)
                  +-> REJECTED (with a reason, back to the maker)        anything not yet run -> CANCELLED

What keeps this honest:
* the maker and the checker are different people - the service says so, and so does the database (`checker_is_not_the_preparer`);
* an approval is for ONE fingerprint of the batch (`snapshot_hash`): anything that changes what would be generated - a family's balance,
  the policy, the selection, an override, the provider - changes the fingerprint, so a stale preview or a stale approval is refused, and
  an approval that no longer matches is withdrawn and the batch goes back to its maker;
* nothing reaches a provider until the batch is approved, and then only through the job queue (see `jobs`), never inside a transaction;
* a family already generated is frozen: it is never regenerated, and what happened to it stays in the batch whatever happens to the rest.

Refusals raised AFTER a state change was committed (a withdrawn approval) are raised outside the transaction, so the change is kept.
"""

from django.db import transaction
from django.utils import timezone
from rest_framework.exceptions import NotFound

from apps.bankconnect import permissions as authority
from apps.bankconnect.constants import ConnectionStatus
from apps.bankconnect.models import CollectionProviderConnection
from apps.bankconnect.providers import registry
from apps.core.scrub import scrub

from . import audit, evaluation, policy
from .constants import (
    EDITABLE_STATUSES,
    OVERRIDABLE_STATUSES,
    ArrearsPolicy,
    BatchStatus,
    Eligibility,
    GenerationStatus,
    OverrideScope,
)
from .errors import CollectionRefused
from .models import CollectionBatchEvent, CollectionGenerationBatch, CollectionGenerationBatchItem

MIN_REJECTION_WORDS = 3
#: Events that mean a person worked on the batch: whoever did any of these can never approve it.
MAKER_KINDS = (
    "created", "preview_refreshed", "selection_changed", "override_set", "override_cleared", "arrears_chosen", "policy_changed", "revised",
    "submitted", "retried",
)
FROZEN = (GenerationStatus.SUCCESS,)


# -- finding, locking, recording ------------------------------------------------------------------------


def get_batch(membership, batch_id, *, lock: bool = False) -> CollectionGenerationBatch:
    """Only ever this school's own: another school's batch answers 404, as if it did not exist."""
    query = CollectionGenerationBatch.objects.select_related("session", "term", "provider_connection", "prepared_by__user").filter(
        school=membership.school, id=batch_id
    )
    batch = (query.select_for_update(of=("self",)) if lock else query).first()
    if batch is None:
        raise NotFound("That collection batch was not found.")
    return batch


def _event(batch, kind: str, actor=None, **detail) -> CollectionBatchEvent:
    return CollectionBatchEvent.objects.create(batch=batch, kind=kind, actor=actor, version=batch.version, detail=scrub(detail))


def _need(membership, check, message: str, code: str) -> None:
    if not check(membership):
        raise CollectionRefused(message, code)


def _need_prepare(membership) -> None:
    _need(membership, authority.can_prepare, "Only the owner, or someone the owner has authorised, can prepare a collection batch.", "not_preparer")


def _need_approve(membership) -> None:
    _need(membership, authority.can_approve, "Only the owner, or someone the owner has authorised, can approve a collection batch.", "not_approver")


def makers_of(batch) -> set:
    """Everyone who prepared, changed or submitted this batch."""
    ids = {batch.prepared_by_id, batch.submitted_by_id}
    ids.update(CollectionBatchEvent.objects.filter(batch=batch, kind__in=MAKER_KINDS).values_list("actor_id", flat=True))
    ids.discard(None)
    return ids


# -- the active provider ------------------------------------------------------------------------------


def _active_connection(school) -> CollectionProviderConnection:
    connection = CollectionProviderConnection.objects.filter(school=school, is_active_provider=True).first()
    if connection is None:
        raise CollectionRefused("Choose the school's active collection provider first. Accounts are generated by that provider.", "no_active_provider")
    if connection.status != ConnectionStatus.CONNECTED:
        raise CollectionRefused("The active collection provider is not working. Test it or replace its credentials first.", "provider_not_connected")
    if registry.get_connector(connection.provider) is None:
        raise CollectionRefused("That provider is not available on this server.", "provider_unavailable")
    return connection


def _still_the_provider(batch) -> None:
    """The batch was made for the school's active provider and may only be approved and run while it still is."""
    current = CollectionProviderConnection.objects.filter(pk=batch.provider_connection_id).first()
    if current is None or not current.is_active_provider:
        raise CollectionRefused(
            "The school's active collection provider has changed since this batch was prepared. Refresh the preview, so it is prepared for the current provider.",
            "provider_changed",
        )
    if current.status != ConnectionStatus.CONNECTED:
        raise CollectionRefused("The active collection provider is not working. Test it or replace its credentials first.", "provider_not_connected")


# -- the preview ---------------------------------------------------------------------------------------


def item_state(item) -> dict:
    """An item's stored fields in the shape the fingerprint reads."""
    return {
        "selected": item.selected, "previous_arrears_minor": item.previous_arrears_minor, "current_due_minor": item.current_due_minor,
        "credit_minor": item.credit_minor, "proposed_collection_minor": item.proposed_collection_minor, "eligibility_status": item.eligibility_status,
        "eligibility_override": item.eligibility_override, "override_reason": item.override_reason, "arrears_policy": item.arrears_policy,
        "custom_arrears_receivable_ids": list(item.custom_arrears_receivable_ids or []), "policy_snapshot": item.policy_snapshot or {},
        "existing_action": (item.policy_snapshot or {}).get("existingAction", ""), "missing": (item.policy_snapshot or {}).get("missing", []),
    }


def _apply_state(item, state: dict) -> None:
    for name in (
        "selected", "previous_arrears_minor", "current_due_minor", "credit_minor", "proposed_collection_minor", "arrears_breakdown", "arrears_policy",
        "eligibility_status", "eligibility_note", "eligibility_override", "custom_arrears_receivable_ids",
    ):
        setattr(item, name, state[name])
    item.policy_snapshot = {**state["policy_snapshot"], "existingAction": state["existing_action"], "missing": state["missing"]}
    if not state["eligibility_override"]:
        item.override_reason = ""
    if item.generation_status not in (GenerationStatus.SUCCESS, GenerationStatus.GENERATING):
        if item.generation_status not in (GenerationStatus.FAILED, GenerationStatus.RETRYING) or not state["selected"]:
            item.generation_status = GenerationStatus.PENDING if state["selected"] else GenerationStatus.SKIPPED
    item.fingerprint = evaluation.fingerprint(item.family_id, item_state(item))


def _selected_entries(items) -> list[tuple]:
    return [(i.family_id, i.fingerprint) for i in items if i.selected]


def _totals(batch, items) -> None:
    chosen = [i for i in items if i.selected]
    batch.family_count = len(items)
    batch.selected_count = len(chosen)
    batch.total_previous_arrears_minor = sum(i.previous_arrears_minor for i in chosen)
    batch.total_current_due_minor = sum(i.current_due_minor for i in chosen)
    batch.total_collection_minor = sum(i.proposed_collection_minor for i in chosen)


def _settle_hash(batch, items, actor, kind: str, **detail) -> bool:
    """Bring the batch's totals and fingerprint into line with its items. If what would be generated changed, the version rises and the
    change is recorded. Returns whether it changed."""
    _totals(batch, items)
    new = evaluation.batch_hash(batch, _selected_entries(items))
    changed = new != batch.snapshot_hash
    if changed:
        if batch.snapshot_hash:  # the first fingerprint is version 1; every later change raises it
            batch.version += 1
        batch.snapshot_hash = new
    batch.save()
    _event(batch, kind, actor, changed=changed, selected=batch.selected_count, **detail)
    return changed


def _rebuild(batch, actor, kind: str = "preview_refreshed") -> None:
    """Work every family out again from the ledger as it is now, keeping each person's own choices where they still make sense.
    Families already generated are frozen. Nothing is called at any provider and nothing in the ledger changes."""
    universe = evaluation.build_universe(batch)
    context = evaluation.policy_context(batch)
    batch.policy_snapshot = context.base_policy().snapshot()
    items = {i.family_id: i for i in CollectionGenerationBatchItem.objects.select_related("family").filter(batch=batch)}
    seen = set()
    for family in universe.families:
        seen.add(family.id)
        prior = items.get(family.id)
        if prior is not None and prior.generation_status in FROZEN:
            continue
        ev = evaluation.evaluate(universe, family, context.for_family(family.id), prior)
        state = evaluation.state_of(ev, prior)
        if prior is None:
            prior = CollectionGenerationBatchItem(batch=batch, school=batch.school, family=family)
            items[family.id] = prior
        _apply_state(prior, state)
        prior.save()
    for family_id, item in items.items():
        if family_id in seen or item.generation_status in FROZEN:
            continue
        item.selected = False
        item.eligibility_status = Eligibility.EXCLUDED
        item.eligibility_note = "This family is no longer active at the school."
        item.generation_status = GenerationStatus.SKIPPED
        item.fingerprint = evaluation.fingerprint(item.family_id, item_state(item))
        item.save()
    batch.preview_built_at = timezone.now()
    _settle_hash(batch, list(items.values()), actor, kind)


# -- making and editing a draft -------------------------------------------------------------------------


@transaction.atomic
def create_batch(membership, *, session, term=None, title="", policy_values=None, reason="") -> CollectionGenerationBatch:
    """Start a draft for a session and term, for the school's ACTIVE provider, and build its preview. Nothing is sent to any provider."""
    _need_prepare(membership)
    school = membership.school
    if session is None or session.school_id != school.id:
        raise CollectionRefused("Choose one of the school's sessions.", "session_required")
    if term is not None and term.session_id != session.id:
        raise CollectionRefused("That term is not in that session.", "term_not_in_session")
    connection = _active_connection(school)
    batch = CollectionGenerationBatch.objects.create(
        school=school, session=session, term=term, provider_connection=connection, provider=connection.provider, environment=connection.environment,
        title=" ".join(str(title or "").split())[:120], prepared_by=membership,
    )
    _event(batch, "created", membership, session=str(session.id), term=str(term.id) if term else "", provider=connection.provider)
    if policy_values:
        policy.set_override(membership, scope=OverrideScope.BATCH, batch=batch, values=policy_values, reason=reason, allow_prepare=True)
    _rebuild(batch, membership)
    audit.record(school, "batch_created", actor=membership, obj=batch, provider=connection.provider)
    return batch


def _editable(membership, batch_id) -> CollectionGenerationBatch:
    """The batch, locked, for a maker to change. A rejected batch goes back to being a draft the moment they start revising it."""
    _need_prepare(membership)
    batch = get_batch(membership, batch_id, lock=True)
    if batch.status not in EDITABLE_STATUSES:
        raise CollectionRefused("This batch can no longer be changed. Only a draft, or a batch that was rejected, can be edited.", "not_editable")
    if batch.status == BatchStatus.REJECTED:
        batch.status = BatchStatus.DRAFT
        batch.save(update_fields=["status", "updated_at"])
        _event(batch, "revised", membership, after="rejection")
    return batch


def _check_version(batch, expected_version) -> None:
    if expected_version is not None and int(expected_version) != batch.version:
        raise CollectionRefused(
            "This batch was changed since you last looked at it. Refresh it and try again.", "stale_preview", version=batch.version, snapshotHash=batch.snapshot_hash
        )


@transaction.atomic
def refresh_preview(membership, batch_id, *, expected_version=None) -> CollectionGenerationBatch:
    batch = _editable(membership, batch_id)
    _check_version(batch, expected_version)
    _repoint(batch, membership)
    _rebuild(batch, membership)
    return batch


def _repoint(batch, actor) -> None:
    """A draft made for a provider that is no longer the active one is moved to the school's current active provider when it is refreshed."""
    connection = _active_connection(batch.school)
    if connection.id != batch.provider_connection_id:
        _event(batch, "provider_changed", actor, was=batch.provider, now=connection.provider)
        batch.provider_connection, batch.provider, batch.environment = connection, connection.provider, connection.environment
        batch.save()


@transaction.atomic
def set_selection(membership, batch_id, *, select=(), deselect=(), select_all_eligible=False, deselect_all=False, expected_version=None):
    """Select and deselect families. A family can only be selected when it can really be given an account."""
    batch = _editable(membership, batch_id)
    _check_version(batch, expected_version)
    items = list(CollectionGenerationBatchItem.objects.select_related("family").filter(batch=batch))
    by_id = {str(i.id): i for i in items}
    wanted = {str(x) for x in select}
    unwanted = {str(x) for x in deselect}
    unknown = (wanted | unwanted) - set(by_id)
    if unknown:
        raise CollectionRefused("Some of those families are not in this batch.", "item_not_found")
    refused = []
    for item in items:
        key = str(item.id)
        if item.generation_status in FROZEN:
            if key in wanted | unwanted:
                refused.append(f"{item.family.display_name} already has an account from this batch")
            continue
        if deselect_all or key in unwanted:
            item.selected = False
        if select_all_eligible and item.eligibility_status == Eligibility.ELIGIBLE:
            item.selected = True
        if key in wanted:
            allowed, why = evaluation.can_select(item.eligibility_status, override=item.eligibility_override)
            if not allowed:
                refused.append(f"{item.family.display_name}: {why}")
            else:
                item.selected = True
    if refused:
        raise CollectionRefused("; ".join(refused[:5]), "cannot_select")
    for item in items:
        if item.generation_status not in FROZEN:
            item.generation_status = GenerationStatus.PENDING if item.selected else GenerationStatus.SKIPPED
            item.fingerprint = evaluation.fingerprint(item.family_id, item_state(item))
            item.save()
    _settle_hash(batch, items, membership, "selection_changed", select=len(wanted), deselect=len(unwanted), all_eligible=bool(select_all_eligible), none=bool(deselect_all))
    return batch


def _item(batch, item_id) -> CollectionGenerationBatchItem:
    item = CollectionGenerationBatchItem.objects.select_related("family").filter(batch=batch, id=item_id).first()
    if item is None:
        raise CollectionRefused("That family is not in this batch.", "item_not_found")
    if item.generation_status in FROZEN:
        raise CollectionRefused("That family already has an account from this batch.", "already_generated")
    return item


@transaction.atomic
def set_eligibility_override(membership, batch_id, item_id, *, reason, expected_version=None):
    """Include a family the school's policy would not include, on an authorised person's say-so. The reason is kept with who said it. It
    does NOT erase what the family owes: the ledger is untouched and the arrears stay owed."""
    batch = _editable(membership, batch_id)
    _check_version(batch, expected_version)
    item = _item(batch, item_id)
    if item.eligibility_status not in OVERRIDABLE_STATUSES:
        raise CollectionRefused("This family does not need an override.", "no_override_needed")
    if item.eligibility_status == Eligibility.EXCLUDED and not authority.can_manage_policy(membership):
        raise CollectionRefused("The school's policy leaves this family out. Only someone who manages the collection policy can override that.", "not_policy_manager")
    reason = policy.clean_reason(batch.school, reason, sensitive=True, what="an eligibility override")
    item.eligibility_override, item.override_reason, item.override_by, item.override_at = True, reason, membership, timezone.now()
    item.selected = True
    item.generation_status = GenerationStatus.PENDING
    item.save()
    audit.record(batch.school, "eligibility_overridden", actor=membership, obj=item, batch=str(batch.id), family=str(item.family_id), reason=reason,
                 previous_arrears_minor=item.previous_arrears_minor)
    _rebuild(batch, membership, "override_set")
    return batch


@transaction.atomic
def clear_eligibility_override(membership, batch_id, item_id, *, expected_version=None):
    batch = _editable(membership, batch_id)
    _check_version(batch, expected_version)
    item = _item(batch, item_id)
    if not item.eligibility_override:
        raise CollectionRefused("This family has no override.", "no_override")
    item.eligibility_override, item.override_reason, item.override_by, item.override_at = False, "", None, None
    item.selected = False
    item.save()
    audit.record(batch.school, "eligibility_override_cleared", actor=membership, obj=item, batch=str(batch.id), family=str(item.family_id))
    _rebuild(batch, membership, "override_cleared")
    return batch


@transaction.atomic
def choose_arrears(membership, batch_id, item_id, *, receivable_ids, expected_version=None):
    """Where the arrears policy lets a person choose, pick which earlier balances go into the family's collection target."""
    batch = _editable(membership, batch_id)
    _check_version(batch, expected_version)
    item = _item(batch, item_id)
    if item.arrears_policy != ArrearsPolicy.CUSTOM_SELECTION:
        raise CollectionRefused("The arrears policy for this family does not let you choose balances.", "not_custom_arrears")
    if not isinstance(receivable_ids, (list, tuple)):
        raise CollectionRefused("Send the balances as a list.", "invalid_arrears")
    known = {b["receivableId"] for b in item.arrears_breakdown or []}
    chosen = {str(r) for r in receivable_ids}
    if chosen - known:
        raise CollectionRefused("Some of those balances are not among what this family owes for earlier terms.", "invalid_arrears")
    item.custom_arrears_receivable_ids = sorted(chosen)
    item.save()
    audit.record(batch.school, "arrears_chosen", actor=membership, obj=item, batch=str(batch.id), family=str(item.family_id), count=len(chosen))
    _rebuild(batch, membership, "arrears_chosen")
    return batch


@transaction.atomic
def set_batch_policy(membership, batch_id, *, values, reason="", expected_version=None):
    """A policy for just this batch (for example dynamic accounts this term). It sits above the term and below any family's own override."""
    batch = _editable(membership, batch_id)
    _check_version(batch, expected_version)
    policy.set_override(membership, scope=OverrideScope.BATCH, batch=batch, values=values, reason=reason, allow_prepare=True)
    _rebuild(batch, membership, "policy_changed")
    return batch


@transaction.atomic
def rename(membership, batch_id, title: str):
    batch = _editable(membership, batch_id)
    batch.title = " ".join(str(title or "").split())[:120]
    batch.save(update_fields=["title", "updated_at"])
    return batch


# -- freshness ----------------------------------------------------------------------------------------


def live_hash(batch) -> str:
    """The fingerprint the batch WOULD have if it were rebuilt right now, from the ledger, the policy and the accounts as they are.
    Families already generated count as they were. Nothing is written."""
    universe = evaluation.build_universe(batch)
    context = evaluation.policy_context(batch)
    by_id = {f.id: f for f in universe.families}
    entries = []
    for item in CollectionGenerationBatchItem.objects.filter(batch=batch, selected=True).select_related("family"):
        if item.generation_status in FROZEN:
            entries.append((item.family_id, item.fingerprint))
            continue
        family = by_id.get(item.family_id)
        if family is None:
            continue  # no longer active: it drops out, and so the hash changes
        state = evaluation.state_of(evaluation.evaluate(universe, family, context.for_family(family.id), item), item)
        if state["selected"]:
            probe = CollectionGenerationBatchItem(
                batch=batch, family=family, school=batch.school, selected=True, override_reason=item.override_reason,
                custom_arrears_receivable_ids=item.custom_arrears_receivable_ids,
            )
            _apply_state(probe, state)
            entries.append((item.family_id, probe.fingerprint))
    return evaluation.batch_hash(batch, entries, context.base_policy().snapshot())


def _withdraw(batch, actor, why: str) -> None:
    """The batch no longer matches what was submitted or approved: the approval is withdrawn and the batch goes back to its maker."""
    was = batch.status
    batch.status = BatchStatus.DRAFT
    for name in ("approved_by", "approved_at", "submitted_by", "submitted_at"):
        setattr(batch, name, None)
    batch.approved_snapshot_hash, batch.approved_version = "", None
    batch.version += 1
    batch.save()
    _event(batch, "approval_invalidated", actor, was=was, why=why)
    audit.record(batch.school, "batch_approval_withdrawn", actor=actor, obj=batch, was=was, why=why)


# -- submit, approve, reject ------------------------------------------------------------------------


def _problems(batch, items) -> list[str]:
    problems = []
    chosen = [i for i in items if i.selected]
    if not chosen:
        problems.append("Select at least one family.")
    if (batch.policy_snapshot or {}).get("problems"):
        problems.extend(batch.policy_snapshot["problems"])
    for item in chosen:
        allowed, why = evaluation.can_select(item.eligibility_status, override=item.eligibility_override)
        if not allowed:
            problems.append(f"{item.family.display_name}: {why}")
        for issue in (item.policy_snapshot or {}).get("problems") or []:
            problems.append(f"{item.family.display_name}: {issue}")
    return problems


def submit(membership, batch_id, *, expected_hash: str = "", expected_version=None) -> CollectionGenerationBatch:
    """Send the batch to be approved. What is submitted is exactly what the maker was looking at: a stale preview is refused."""
    stale = None
    with transaction.atomic():
        _need_prepare(membership)
        batch = get_batch(membership, batch_id, lock=True)
        if batch.status not in EDITABLE_STATUSES:
            raise CollectionRefused("Only a draft, or a rejected batch, can be submitted.", "not_editable")
        _check_version(batch, expected_version)
        if expected_hash and expected_hash != batch.snapshot_hash:
            raise CollectionRefused("This batch was changed since you last looked at it. Refresh it and try again.", "stale_preview", version=batch.version, snapshotHash=batch.snapshot_hash)
        _still_the_provider(batch)
        items = list(CollectionGenerationBatchItem.objects.select_related("family").filter(batch=batch))
        problems = _problems(batch, items)
        if problems:
            raise CollectionRefused(problems[0], "batch_not_ready", problems=problems[:20])
        if live_hash(batch) != batch.snapshot_hash:
            stale = "What families owe, the policy or their accounts changed since the preview was built. Refresh the preview and look at it again."
        else:
            if batch.status == BatchStatus.REJECTED:
                _event(batch, "revised", membership, after="rejection")
            batch.status = BatchStatus.PENDING_APPROVAL
            batch.submitted_by, batch.submitted_at = membership, timezone.now()
            batch.rejected_by = batch.rejected_at = None
            batch.rejection_reason = ""
            batch.save()
            _event(batch, "submitted", membership, hash=batch.snapshot_hash, selected=batch.selected_count, total=batch.total_collection_minor)
            audit.record(batch.school, "batch_submitted", actor=membership, obj=batch, selected=batch.selected_count, total_minor=batch.total_collection_minor)
    if stale:
        raise CollectionRefused(stale, "stale_preview", version=batch.version, snapshotHash=batch.snapshot_hash)
    return batch


def approve(membership, batch_id, *, expected_hash: str, manual_item_ids=()) -> CollectionGenerationBatch:
    """Approve exactly what was submitted. The approver is never anyone who prepared, changed or submitted the batch."""
    withdrawn = None
    with transaction.atomic():
        _need_approve(membership)
        batch = get_batch(membership, batch_id, lock=True)
        if batch.status != BatchStatus.PENDING_APPROVAL:
            raise CollectionRefused("This batch is not waiting for approval.", "not_pending")
        if membership.id in makers_of(batch):
            raise CollectionRefused("You prepared or changed this batch, so someone else must approve it.", "maker_cannot_approve")
        if not expected_hash or expected_hash != batch.snapshot_hash:
            raise CollectionRefused("This batch changed after you opened it. Open it again and review what it now contains.", "stale_approval", version=batch.version, snapshotHash=batch.snapshot_hash)
        _still_the_provider(batch)
        if live_hash(batch) != batch.snapshot_hash:
            withdrawn = "What families owe, the policy or their accounts changed since this batch was submitted."
            _withdraw(batch, membership, withdrawn)
        else:
            items = list(CollectionGenerationBatchItem.objects.select_related("family").filter(batch=batch, selected=True))
            allowed = {str(x) for x in manual_item_ids}
            needing = [i for i in items if i.eligibility_status == Eligibility.MANUAL_APPROVAL and not i.manual_approved_by_id]
            missing = [i for i in needing if str(i.id) not in allowed]
            if missing:
                raise CollectionRefused(
                    f"{len(missing)} families need your approval one by one: " + ", ".join(i.family.display_name for i in missing[:5]) + ".",
                    "manual_approval_needed", itemIds=[str(i.id) for i in missing],
                )
            now = timezone.now()
            for item in needing:
                if item.override_by_id == membership.id:
                    raise CollectionRefused("You overrode this family yourself, so someone else must approve it.", "maker_cannot_approve")
                item.manual_approved_by, item.manual_approved_at = membership, now
                item.save(update_fields=["manual_approved_by", "manual_approved_at", "updated_at"])
                audit.record(batch.school, "family_manually_approved", actor=membership, obj=item, batch=str(batch.id), family=str(item.family_id))
            batch.status = BatchStatus.APPROVED
            batch.approved_by, batch.approved_at = membership, now
            batch.approved_snapshot_hash, batch.approved_version = batch.snapshot_hash, batch.version
            batch.save()
            _event(batch, "approved", membership, hash=batch.snapshot_hash, selected=batch.selected_count, total=batch.total_collection_minor)
            audit.record(batch.school, "batch_approved", actor=membership, obj=batch, hash=batch.snapshot_hash, selected=batch.selected_count, total_minor=batch.total_collection_minor)
    if withdrawn:
        raise CollectionRefused(withdrawn + " Its approval was withdrawn and it is back with the maker.", "batch_changed", version=batch.version)
    return batch


@transaction.atomic
def reject(membership, batch_id, *, reason: str) -> CollectionGenerationBatch:
    """Send it back to the maker, with the reason. Everything stays: the batch, its history and the reason."""
    _need_approve(membership)
    batch = get_batch(membership, batch_id, lock=True)
    if batch.status != BatchStatus.PENDING_APPROVAL:
        raise CollectionRefused("This batch is not waiting for approval.", "not_pending")
    if membership.id in makers_of(batch):
        raise CollectionRefused("You prepared or changed this batch, so someone else must decide on it.", "maker_cannot_approve")
    reason = " ".join(str(reason or "").split())
    if len(reason.split()) < MIN_REJECTION_WORDS:
        raise CollectionRefused("Say why you are rejecting it, so the person who prepared it knows what to change.", "reason_required")
    if len(reason) > 500:
        raise CollectionRefused("A reason can be at most 500 characters.", "reason_too_long")
    batch.status = BatchStatus.REJECTED
    batch.rejected_by, batch.rejected_at, batch.rejection_reason = membership, timezone.now(), reason
    batch.save()
    _event(batch, "rejected", membership, reason=reason)
    audit.record(batch.school, "batch_rejected", actor=membership, obj=batch, reason=reason)
    return batch


@transaction.atomic
def cancel(membership, batch_id, *, reason: str = "") -> CollectionGenerationBatch:
    _need_prepare(membership)
    batch = get_batch(membership, batch_id, lock=True)
    if batch.status not in (BatchStatus.DRAFT, BatchStatus.PENDING_APPROVAL, BatchStatus.REJECTED, BatchStatus.APPROVED, BatchStatus.FAILED):
        raise CollectionRefused("A batch that is generating, or that already made accounts, cannot be cancelled.", "cannot_cancel")
    batch.status = BatchStatus.CANCELLED
    batch.cancelled_by, batch.cancelled_at = membership, timezone.now()
    batch.save()
    CollectionGenerationBatchItem.objects.filter(batch=batch).exclude(generation_status__in=FROZEN).update(selected=False, generation_status=GenerationStatus.SKIPPED)
    _event(batch, "cancelled", membership, reason=" ".join(str(reason or "").split())[:300])
    audit.record(batch.school, "batch_cancelled", actor=membership, obj=batch)
    return batch
